### ISSUE TITLE
Add cohen's dz for paired samples.

### ISSUE THREAD

**Issue by mno-93** [stonegold546/cohens_d_calculators#29]
Dear stonegold546,

thanks for providing this great tool. I just wanted to recommend that you could add the standard d-value (d_z) often used (even if not recommended by Lakens) for paired measurements as stated in the beginning in the d section of Lakens article:
https://www.frontiersin.org/articles/10.3389/fpsyg.2013.00863/full

**Comment by stonegold546** [comment]
Hello, sorry for the late-ish reply. What reason would there be to include it other than its popularity?

**Comment by mno-93** [comment]
Hey,

it's just a recommendation for completeness, not more. The tool is really helpful as it is right now - just thought of it when I read Lakens again. Could be interesting to see different results when using the other formula.

**Comment by stonegold546** [comment]
Once again, sorry for the late reply.

I don't think completeness is a sufficient reason, one could expand the metrics endlessly. Also, I do not think d_z is a good approach. Simple reason being you can have an unusually large _d_ when you have highly correlated repeated measurements. And since most people wrongly (in my opinion) think of _d_ as a neutral metric (scale / design agnostic), d_z can mislead.

Also, d_rm is an attempt at a design-neutral d_z - so I think having d_rm there is enough.
